version: '3.8'
  
services:
  pg-db-user:
    container_name: pg-db-user
    image: postgres
    ports:
      - "${PG_PORT}:5432"
    restart: on-failure
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - PO
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PG_DB} -U ${PG_USER}"]
      interval: 0.5s
      timeout: 10s
      retries: 10

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  otel-collector:
    depends_on:
      - jaeger-all-in-one
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-collector/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "${OTLP_PORT}:4317"   # OTLP gRPC receiver
      - "4418:4318"   # OTLP http receiver
      - "13133:13133" # health_check extension
      - "1888:1888"   # pprof extension
      - "55679:55679" # zpages extension
  db-migrator:
    depends_on:
      pg-db-user:
        condition: service_healthy
    container_name: db-migrator-user
    image: hub.mceasy.com/db-migrator:v1.0
    environment:
      CONFIG_TYPE: env
      PG_HOST: pg-db-user
      PG_PORT: 5432
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DBNAME: ${PG_DB}
    volumes:
      - ./database/migrations/versions:/app/alembic/versions
      - ./database/migrations/schema.py:/app/schema.py
    stdin_open: true